#include<stdio.h>

int main(){
    printf("Now in those days there was in the land of Helsinki a young scholar named \033[34mmLinus\033[0m the Torvald. \033[34mLinus\033[0m was a devout man, a disciple of \033[34mRMS\033[0m and mighty in the spirit of \033[34mTuring\033[0m , \033[34mvon Neumann\033[0m and \033[34mMoore\033[0m. One day as he was meditating on the Architecture , \033[34mLinus\033[0m fell into a trance and was granted a vision. And in the vision he saw a great Penguin , serene and well-favoured , sitting upon an ice floe eating fish. And at the sight of the Penguin Linus was deeply afraid , and he cried unto the spirits of \033[34mTuring\033[0m , \033[34mvon Neumann\033[0m and \033[34mMoore\033[0m for an interpretation of the dream.\n\n");

    printf("And in the dream the spirits of \033[34mTuring\033[0m , \033[34mvon Neumann\033[0m and \033[34mMoore\033[0m answered and spoke unto him, saying , \033[31m\"Fear not, Linus , most beloved hacker. You are exceedingly cool and froody. The great Penguin which you see is an Operating System which you shall create and deploy unto the earth. The ice-floe is the earth and all the systems thereof , upon which the Penguin shall rest and rejoice at the completion of its task. And the fish on which the Penguin feeds are the crufty Licensed codebases which swim beneath all the earth’s systems. The Penguin shall hunt and devour all that is crufty , gnarly and bogacious; all code which wriggles like spaghetti , or is infested with blighting creatures , or is bound by grave and perilous Licences shall it capture. And in capturing shall it replicate , and in replicating shall it document , and in documentation shall it bring freedom , serenity and most cool froodiness to the earth and all who code therein.\"\033[0m\n\n");

    printf("\033[34mLinus\033[0m rose from meditation and created a tiny Operating System Kernel as the dream had foreshewn him; in the manner of \033[34mRMS\033[0m, he released the Kernel unto the World Wide Web for all to take and behold. And in the fulness of Internet Time the Kernel grew and replicated , becoming most cool and exceedingly froody , until at last it was recognised as indeed a great and mighty Penguin , whose name was Tux. And the followers of \033[34mLinus\033[0m took refuge in the Kernel , the Libraries and the Utilities; they installed Distribution after Distribution , and made sacrifice unto the GNU and the Penguin , and gave thanks to the spirits of \033[34mTuring\033[0m , \033[34mvon Neumann\033[0m and \033[34mMoore\033[0m , for their deliverance from the hand of Microsoft. And this was the beginning of the Fourth Age, the age of Open Source.\n");

    return 0;
}
